- name: will wait till reachable
  hosts: all
  gather_facts: false # we just created the EC2 machine, so we want for the machine to become accessible before gathering facts
  ignore_unreachable: true
  vars_files:
        ec2Id:
  tasks:
        - name: Display output from ec2 stack
          ansible.builtin.debug:
            msg: "the output from the ec2 instance is : {{ ec2ID }}"

        - name: Wait for system to become reachable
          ansible.builtin.wait_for_connection:
                timeout: 180
                
        - name: Gather facts for the first time
          ansible.builtin.setup:
          